### ISSUE TITLE
Installer gets stuck during Partitioning

### ISSUE THREAD

**Issue by kalikiana** [yast/d-installer#111]
I got excited when I read [today's blog post](https://yast.opensuse.org/blog/2022-03-31/d-installer-first-public-release) and decided to give it a go on a spare machine.

Unfortunately the installation got stuck during partitioning.

- There was nothing to select, and the two combo boxes were empty. I **assume** this was expected since this is a very early version.
- I was not prompted for networking details.
- `/var/log/Yast2/y2log` contains `No base product, I won't create flavor cache`. Not sure what else might be relevant

I do realize the blog said it's better to try a VM. But I assumed it should still work on bare metal? 🤔

**Comment by kalikiana** [comment]
> Regarding the partitioning, it looks like the installer did not find any suitable disk. Perhaps you could share your y2log and your /var/log/YaST2/storage-inst directory with us in order to debug the problem.

Not sure how to share the logs. Something I realized after rebooting however is the machine set itself to RAID rather than AHCI which also caused the regular installer to not find any disks until I changed it back. So I'm guessing this is the same issue.

**Comment by imobachgs** [comment]
D-Installer code is based on the regular installer, so the issue might be the same. We need to improve error handling so D-Installer does not look stuck when something goes wrong.

We plan to work on that [sooner than later](https://github.com/yast/d-installer/issues/123), though.

**Comment by imobachgs** [comment]
Hi,

We have released a new version of the ISO. It would be nice if you could give it a try. If it still gets blocked, it would be helpful if you extract the logs so we can inspect them. To do that, you need to change to a text console, log in as root (root/linux) and run the `save_y2logs` command.

You can grab the new version from https://build.opensuse.org/package/binaries/YaST:Head:D-Installer/d-installer-live/images

Thanks in advance!

**Comment by imobachgs** [comment]
Please, let us know if the problem persists because we have introduced quite some changes. Thanks!
