### ISSUE TITLE
The remember password dialog at the very first experience with installer feels odd

### ISSUE THREAD

**Issue by lkocman** [yast/d-installer#113]
An observation I was quite surprised when I experienced the installer for the first time. 

The very first dialog - I wanted to add my expected user/password for the host being installed. My fault I suppose

And the second odd thing is remembering the credentials for system install from livecd which I do not plan to do repeatedly. Perhaps we could skip that. We should minimize the 

![d_installer_save_login](https://user-images.githubusercontent.com/510119/161271501-be574d1d-c610-408e-9556-5d5633506a23.png)
amount of user input (e.g. clicks), and this one seems to be unnecessary.

**Comment by imobachgs** [comment]
Hi @lkocman,

Thanks for giving it a try.

The first user/password dialog might be confusing, that's right. It is used to log into *cockpit*, but we would like to get rid of that login screen if you are installing locally. Or, at least, give the user a hint about what is expected there.

About remembering the password, you are right. That's something we need to disable so users do not get annoyed for nothing.

Thanks!
