### ISSUE TITLE
Cannot reach login with 1G and other minor issues

### ISSUE THREAD

**Issue by jknphy** [yast/d-installer#115]
First of all, congrats for the good work for this prototype to happen.

I found some things to improve:
- Login screen is not reachable with 1GB, after 5 minutes I still in "Loading installation environment, please wait." Login screen appears afterwards but it is practically unresponsive (so testing with 2G from now on). I guess with 1GB should enough.
- Labels Username and Password are links in Login screen, also in Product dialog, is that expected? looks like it is expected some info when clicking on them.
- Once a different language different from English (US) is selected, when trying to select a different one and press Cancel, the previous language does not stays, it comes back to default English (US).
- When changing focus, for example in Target dialog, from the color perspective, the border for Cancel displays very nice, but the border for Confirm is not really visible when focused.
- If the subvolumes belong to the btrfs partition, perhaps now that the layout will allow to do more fancy things, would it make sense to put those subvolumes right below the partitioning of btrfs. Without thinking in current Tumbleweed installation, I could even expect that at the right side of "for / with btrfs", wdyt?
- In New root password when typing the password, shouldn't disappear the grey label "Do not use a password", it is strange that is there, even from the beginning. When coming back and it is set, then makes sense (perhaps it is too subjective this :) ) btw when changing focus there I noticed it is missing separation between button 'Do not use a password' and 'Cancel'.
- It allows to define user with Username "root" without any warning.
- There are two progress bars in Installing screen, it is not clear what represent each one, I guess on top some current process and the second is for the total, but the steps also do not match with the progress of the second one.
- I tried to force reboot or switch to terminal and type reboot, but I could not boot to check the installed system, I got: "Failed to mount / .snapshots" Dependency failed for Local File Systems.

**Comment by dgdavid** [comment]
> * Labels Username and Password are links in Login screen, also in Product dialog, is that expected? looks like it is expected some info when clicking on them.

No, they are not. They are form labels, which uses the `for` attribute. When you click on them, the related input gets the focus or even toggle their status (checkboxes). Something expected in HTML forms. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by dgdavid** [comment]
> * Once a different language different from English (US) is selected, when trying to select a different one and press Cancel, the previous language does not stays, it comes back to default English (US).

Nice catch, thanks!

**Comment by dgdavid** [comment]
> * When changing focus, for example in Target dialog, from the color perspective, the border for Cancel displays very nice, but the border for Confirm is not really visible when focused.

That's true. We have tried to follow [EOS](https://www.eosdesignsystem.com/) guidelines. Maybe there is something we did wrong or it is something to improve in the EOS side. 

* https://suse.eosdesignsystem.com/focus
* https://suse.eosdesignsystem.com/buttons/usage

A quick check on EOS buttons usage page, shows that the problem is there too. Only for the focus (using the keyboard) but not while hovering the button.

I'll check carefully later.

**Comment by dgdavid** [comment]
> * If the subvolumes belong to the btrfs partition, perhaps now that the layout will allow to do more fancy things, would it make sense to put those subvolumes right below the partitioning of btrfs. Without thinking in current Tumbleweed installation, I could even expect that at the right side of "for / with btrfs", wdyt?

I agree on that, but not sure right now how feasible it is. Maybe @joseivanlopez can tell us more.

**Comment by dgdavid** [comment]
> * In New root password when typing the password, shouldn't disappear the grey label "Do not use a password", it is strange that is there, even from the beginning. When coming back and it is set, then makes sense (perhaps it is too subjective this :) ) 

"Do not use a password" it is disabled when there is no password set (e.g., at the very beginning). Believe or not, we had a lot of discussion on this :) But let me recap the two main points to justify why it is there:

* We're trying to get the summary too crowed. As said in some PR, we decided to _retain_ the essence of the YaST summary, but keeping it simple and usable. The problem with this early version if that we do not have the sections implemented yet, reason why almost all possible actions are available in those popups
* Regarding being always visible… is on purpose. Maybe we are wrong, and we can change it if so, but initially we prefer to not have things that appears and disappears. Thus, users _know in advance_ where they can remove the password after setting it, without thinking too much.

Not sure if @imobachgs wants to clarify anything else.

> btw when changing focus there I noticed it is missing separation between button 'Do not use a password' and 'Cancel'.

Again, nice catch :) The _issue_ there is that those _links_ are actually PatternFly buttons, which I'm not sure if it is ideal. If we put the margin there, then the "Do not use a password" will look a bit farther from other actions... but it's true that current status is ugly when the action is focused. Thanks!

**Comment by dgdavid** [comment]
> It allows to define user with Username "root" without any warning.

This deserves an individual issue, I guess. Thanks!

**Comment by dgdavid** [comment]
> * There are two progress bars in Installing screen, it is not clear what represent each one, I guess on top some current process and the second is for the total, but the steps also do not match with the progress of the second one.

Actually, it is somehow the other way around. On top, we are displaying the overall progress, while the second and thinner bar represent the progress of the current steps.

How to deal with progress information is something we continue discussing / changing / improving even in YaST.

**Comment by dgdavid** [comment]
@jknphy Thanks a ton for the detailed feedback. Much appreciated!

**Comment by joseivanlopez** [comment]
> > * If the subvolumes belong to the btrfs partition, perhaps now that the layout will allow to do more fancy things, would it make sense to put those subvolumes right below the partitioning of btrfs. Without thinking in current Tumbleweed installation, I could even expect that at the right side of "for / with btrfs", wdyt?
> 
> I agree on that, but not sure right now how feasible it is. Maybe @joseivanlopez can tell us more.

Yes, I would like to see something like that in the future. Sadly, we cannot achieve it with the current data. A subvolume action does not have any reference to its parent Btrfs. Of course, this is something we could improve, even for YaST.  But note that threre are some cases to consider: we still need to show actions for removing existing subvolumes, for example, when you are reusing a partititon that was previoulsy formatted as Btrfs, and we have to consider multi-device Btrfs, too. Everything is doable, but even this apparently small change implies several use cases.

**Comment by dgdavid** [comment]
> > * Labels Username and Password are links in Login screen, also in Product dialog, is that expected? looks like it is expected some info when clicking on them.
> 
> No, they are not. They are form labels, which uses the `for` attribute. When you click on them, the related input gets the focus or even toggle their status (checkboxes). Something expected in HTML forms. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

But it is true that browsers use to set the `default` value for the CSS `cursor` property for those elements, which is not the case here because [PatternFly is setting it to `pointer`](https://github.com/patternfly/patternfly/blob/dc6cf07d69cbb80026dca7fe43dc28704aabea64/src/patternfly/components/Form/form.scss#L262-L281). Probably, this is the reason @jknphy thought that those elements were hyperlinks.

| Cursor on D-Installer form label | Cursor on Github form label |
|-|-|
| ![How cursor looks on D-Installer form labels](https://user-images.githubusercontent.com/1691872/161972809-56daaf0b-47ad-4ee8-b286-a63dfad8419e.png) | ![How cursor looks on Github profile](https://user-images.githubusercontent.com/1691872/161972878-645b6a6e-a172-4a42-8f84-9a93afde21a3.png) |

Shall we _revert_ this property to the _default_ value?

**Comment by joseivanlopez** [comment]
> Shall we _revert_ this property to the _default_ value?

IMHO, it would depend on the case. For example, I would use `pointer` if something happens when clicking the label (e.g., put the focus on the associated field, check/uncheck the associated checkbox, show a help, etc). Otherwise, I would use `default`.

**Comment by ancorgs** [comment]
How does it look when the cursor is over the text input box itself?

**Comment by dgdavid** [comment]
> I would use `pointer` if something happens when clicking the label (e.g., put the focus on the associated field, check/uncheck the associated checkbox, show a help, etc)

As said, giving the focus to the related input when clicking on them is the case of forms labels, but I have hardly seen the `cursor: pointer` before for them before. It's not so common.

**Comment by dgdavid** [comment]
> How does it look when the cursor is over the text input box itself?

| Cursor over text input | Cursor over checkbox |
|-|-|
| ![Screenshot from 2022-04-06 14-35-13](https://user-images.githubusercontent.com/1691872/161987689-f015f730-f2d7-4263-9cd2-ca0948d5f5e0.png) | ![Screenshot from 2022-04-06 14-35-28](https://user-images.githubusercontent.com/1691872/161987707-6eb15338-a6d4-4f95-80f3-3ed7c2a6dcfd.png) |

**Comment by lslezak** [comment]
Personally I'd keep the default cursor as much as possible and change it only if really needed in some special cases. Changing the cursor might confuse the users...
