### ISSUE TITLE
Allow web/remote installation

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#121]
At this point, trying to access to D-Installer from a remote machine would cause your browser to complain about the SSL certificate. We need to find a better way to handle this case.

This card includes some research, as we need to find the best way to set up a secure connection. Using an unencrypted connection might be an alternative if we do not find a better way.

## Links

* [Cockpit's documentation about SSL/TLS](https://cockpit-project.org/guide/latest/https)
* [Cockpit's authentication documentation](https://github.com/cockpit-project/cockpit/blob/main/doc/authentication.md)

**Comment by tacerus** [comment]
It would be nice if an enterprise administrator had some easy option to bundle their CA and a deployment certificate. Possibly as part of #122 ?

**Comment by imobachgs** [comment]
> It would be nice if an enterprise administrator had some easy option to bundle their CA and a deployment certificate. Possibly as part of #122 ? But of course, for end-users / SOHO, the plain-text route should probably remain an option too.

I agree: we should offer an "easy" way to deploy the certificates/CA or disable the encryption if really needed. Regarding #122, we plan to allow modifying the YAML file from the boot command line too, so you could pass the URL to the certificates to deploy when booting. But that is still under discussion.

**Comment by imobachgs** [comment]
#145 adds support to enable/disable or configure SSL support. Although the settings are read from [d-installer.yaml](https://github.com/yast/d-installer/pull/132) (which is the right way), they cannot be changed without manually modifying the file and restarting the `d-installer` service.

Issue #147 will address it.
