### ISSUE TITLE
Add a mechanism to modify the d-installer configuration

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#147]
Under discussion:

* Stock configuration in /usr/etc.
* Should we split the configuration into smaller files?
* How to inject values when booting? (from a remote file, bootloader options, etc.).

## Use cases

* Adjust a parameter in a single run (e.g., enabling/disabling SSL).
* Company-specific ISOs (beware, we do not have a way to modify the ISO yet).
* Product or add-on specific configuration.
* Architecture or distro-specific configuration.
* Offline medium (URLs need to be adjusted).

## Scope

* Simple design document
* Adapt the Config class to support such cases.
* Read the configuration from the bootloader command line by:
  * Using a URL that points to a file that contains a custom YAML file (to be merged).
  * Specifying the values in the command line (e.g., web.ssl=false).

**Comment by jreidinger** [comment]
One topic that maybe is worth discuss is also how to split different options according to users as I see use cases for:

1. company specific isos ( where iso is modified and then mass deployed )
2. product/addon specific options, e.g. when installer should be used for medium for specific product
3. offline medium ( so urls and some options has to be modified )
4. arch/distro specific configuration that users should not touch
