### ISSUE TITLE
Display the network IP address in the UI

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#159]
D-Installer does not deal with the network configuration at this point. Although we plan to work on that in the near future, it might be useful to display the current IP address (or addresses) in the UI.

As NetworkManager already offers a D-Bus interface, we do not need to roll our own until we decided what we are going to do with the network configuration.

## Tasks

- [ ] Get the IP address(es) from D-Bus NetworkManager interface.
- [ ] Add a React component to display such information. We could also add whether we are using SSL or not.

**Comment by mchf** [comment]
Initial implementation done.
