### ISSUE TITLE
Build a CLI to install the system from an AutoYaST-like profile

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#163]
The idea is to build a command-line interface that allows installing the system using an AutoYaST profile (or something similar). Obviously, just a few settings are available.

## Steps

1. (Optional) Retrieve the profile
2. Configure d-installer through D-Bus according to the settings in the profile.
3. Start and report installation progress.

## Example profile

This is an example of the things that we might support. Or we could use a YAML file if preferred.

```xml
<!-- product selection -->
<software>
  <products t="list">
    <product>SLES</product>
  </products>
</software>

<!-- storage device -->
<partitioning t="list">
  <drive>
    <device>/dev/vda</device>
  </drive>
</partitioning>

<!-- system language -->
<language>
  <language>es_ES</language>
</language>
```

**Comment by joseivanlopez** [comment]
https://github.com/yast/d-installer/pull/179
