### ISSUE TITLE
LUKS activation 'cosmetic' issues

### ISSUE THREAD

**Issue by teclator** [yast/d-installer#165]
## Description

There is some issues that we have detected while installing with some encrypted device present in the system.

![LuksActivation](https://user-images.githubusercontent.com/7056681/169482408-4c988177-206f-4124-922c-0e7f60e9aa80.png)

1. Maybe the question could be reworded as it ask if you want something but it is not a **Yes / No** answer, instead of it it provides a input for the encryption password. What about something like _**"Please, enter the encryption password if you want to decrypt/open it"**_
2. The default action is **Skip** which looks good when there is no password provided but it is still the **default** and **primary action** when a password is provided. What is worst, If the user press **Enter** the dialog is reload just like a reload action. I would expect it to do nothing or submit the default action which in case of password provided would expect it to be decrypt.

**Comment by teclator** [comment]
@dgdavid was already taking some notes when I show him the errors and these are his notes with some ideas for fixing them:

> Observations from Knut:
> 
> The question would be better if it doesn't contain a Yes/No question. Something like "Please, enter the encryption password if you want to decrypt/open it" instead of "Do you want to decrypt it?"
> 
> It feels weird having the "Skip" as the primary action. If I'm not wrong, he prefers having "Decrypt", even though it is disabled until user enters a password
> 
> Note that the user still being able to jumpt to the skip action with the keyboard using just one TAB while "Decrypt" action is disabled
> 
> Hitting Enter is buggy: instead of send the "Decrypt" answer (when possible) it refreshes the app like if the user actually pressed F5
> 
> Which happens because the form wrapping the input is being [implicitely submitted](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission)
> 
> implicit submission mechanism must do nothing if the form has more than one field that blocks implicit submission, and must submit the form element from the form element itself otherwise.
> 
> There are a couple of options to fix that:
> 
> Set the defaultOption as a type=submit.
> 
> PROBLEMS:
> 
> a) there is not a defaultOption for LuksActivation, which became "Skip" (the first option) the "Primary" one... and would be weird mapping the expected "submit" to the "skip" action
> b) a Question is not always a form, but it will always relay in QuestionActions for building the actions (aka options) for answering the question. Not a big deal, the QuestionActions could receive a prop to know if it should use type=submit for defaultOption.
> Add an onSubmit method that prevents the implicit submission if none password has been entered but calls actionCallback("decrypt") otherwise
> 
> To not wrap the input in a form
> 
> To always prevent the implicit submission.
> 
> Others

**Comment by imobachgs** [comment]
Here is the regular installer dialog:

![encrypted-device](https://user-images.githubusercontent.com/15836/180769623-b05fbe08-f8b2-43bd-9f6f-b08d2dae27dd.png)

**Comment by ancorgs** [comment]
In YaST, if you enter the wrong password you get a new pop-up like this:

![failed](https://user-images.githubusercontent.com/3638289/189916062-318d7e49-9a24-4ece-a708-a5a7082aa7e3.png)

Clicking on "ok" opens again the dialog with the "decrypt" and "skip" buttons.

**Comment by ancorgs** [comment]
D-Installer also has a renderAlert() function to show a message in the second (and subsequent) attempts. But according to my tests, the argument `attempt` is always "1".

**Comment by jreidinger** [comment]
@ancorgs yeap, I can confirm it. See the same

**Comment by ancorgs** [comment]
Fixed by #253
