### ISSUE TITLE
Refresh the web UI when a configuration option changes

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#171]
The UI gets refreshed when the status or the storage actions change, no matter where the change comes from (busctl, the new CLI #166, etc.). However, that's not the case for other configuration values. For instance, if you change the language via D-Bus, the web UI does not get updated.

We should implement support to refresh the interface in those situations.

**Comment by jreidinger** [comment]
Do you test that stuff with changed DBus? If we listen to signals about PropertiesChanged, it should update web UI. ( I see that our web UI is a bit inconsistent with it, when some part listen to that signals and some not ).

**Comment by imobachgs** [comment]
We tried that while implementing #166. Each section should listen to the signals it is interested in.

**Comment by imobachgs** [comment]
Implemented in #180.
