### ISSUE TITLE
Avoid showing single product to install

### ISSUE THREAD

**Issue by jengelh** [yast/d-installer#176]
![prod](https://user-images.githubusercontent.com/8861948/171992349-9bb616df-6ffe-4461-8d3e-115e3b43681f.png)

In terms of simplicity: When there is only one product to choose from, don't even display it.

**Comment by imobachgs** [comment]
Hi! We are reworking the product selection, as we plan to support MicroOS too. You can find some discussion about this matter in #192. Most likely we will add a previous step (if there is more than one product), so the first thing you should do is to select the product (if needed). But, please, feel free to share your POV.

PS: sorry for taking so much time to answer, but I overlooked this one (and #177).

**Comment by imobachgs** [comment]
Perhaps you are interested in #200.

**Comment by imobachgs** [comment]
Starting on version 0.4, D-Installer features a product selection screen and handles this case properly.

![Screenshot 2022-07-29 at 08-29-27 D-Installer](https://user-images.githubusercontent.com/15836/181708385-de78df4f-5763-41d3-a433-ab4c9da39b92.png)

* The first step is the product selection screen if there are many products. The user can change the selected product later using the button at the top.

![Screenshot 2022-07-29 at 08-29-54 D-Installer](https://user-images.githubusercontent.com/15836/181708533-c0e6f313-8895-4f63-9629-1612e41fffbf.png)

* If there is only one product, the link to the products selection screen is not available anymore.

![Screenshot 2022-07-29 at 08-33-45 D-Installer](https://user-images.githubusercontent.com/15836/181708578-29f0b0b3-aab6-428d-ae41-f391fa235fce.png)

Thanks for your feedback!

Regards,
Imo
