### ISSUE TITLE
Unable to login to target installation

### ISSUE THREAD

**Issue by jengelh** [yast/d-installer#177]
The D-Installer defaults define neither a root password nor a user with password. When clicking on "Install", there is no warning about this.

![1](https://user-images.githubusercontent.com/8861948/171993744-60bbc9e0-46c8-465d-b8dd-901959cb4d08.png)

The resulting system is unusable, as no login was assigned and there is no X11 autologin.

![2](https://user-images.githubusercontent.com/8861948/171993996-161eda17-af55-4176-961d-0974db39ca02.png)

**Comment by imobachgs** [comment]
Hi @jengelh,

Yes, that's true. The fact is that we plan to add some mechanism to warn the user about this kind of stuff (not only with users). But we are working on other stuff we would like to solve first.

Thanks for the report!
