### ISSUE TITLE
Small UI details

### ISSUE THREAD

**Issue by joseivanlopez** [yast/d-installer#227]
* Pushing enter (e.g., when adding a user) reloads the whole page.
* UI does not go back to product selection when the phase changes to *startup* (e.g., when restarting the manager service).
* The product selection page does not change when a product is selected with the CLI. 
* User section is not correctly updated in UI when a user is added/deleted with the CLI. 
* Storage section does not show the proposal error when using the CLI for selecting a device without enought space (the same happens when reloading with F5).

**Comment by dgdavid** [comment]
>     * Pushing enter (e.g., when adding a user) reloads the whole page.

See https://github.com/yast/d-installer/issues/226

**Comment by joseivanlopez** [comment]
Fixed https://github.com/yast/d-installer/pull/230.
