### ISSUE TITLE
Build a D-Bus interface for the storage proposal

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#264]
To make it possible to build the workflow/interface defined in that document we need some D-Bus interface that allows to configure and execute a proposal.

Let's build a minimal but valuable initial D-Bus interface.

## Requirements

We need to extend/modify the current proposal object so:

- It can be configured with:
  - The set of disks to use for  installation[1]
  - Which disk to use for booting
  - (out of scope now) How to make space in those disks
  - Enable/disable LVM
  - Set an optional encryption password
  - The set of volumes (see below)
- Offers a method to process those settings and return a result (a list of actions)
- Offers a way to get the available devices that can be selected at [1].
- Offers a way to reset the list of volumes to its default value with:
  - Recommended sizes
  - Minimum sizes

In the proposed UI, every time a setting (LVM, encryption) or a volume gets modified then the whole set of volumes is adjusted (see below how modifications in one volume or in the settings can affect others) and the proposal is executed again to refresh the result. We may want to implement that behavior in the D-BUS API or to separate things a bit so the change in settings updates the volumes but doesn't re-calculate the whole result (the UI would need to trigger that separately somehow). Note that the operation is also atomic in the `Y2Storage` side, so doing everything at once would be easier (does not imply any fundamental change in the `Y2Storage` classes and APIs).

## Links

* https://trello.com/c/ONUj4kbd/
* #255

**Comment by joseivanlopez** [comment]
https://github.com/yast/d-installer/pull/268
