### ISSUE TITLE
User is trapped and can't exit in case that he clicks on external link (untrusted site?)

### ISSUE THREAD

**Issue by lkocman** [yast/d-installer#273]
Hello team,

Seems like there is a small trap for user without internet connection in case that user clicks on the about link in the installation summary and later on "github project page" referenced in the text.

The refresh button won't help and there is no "easy" way out. I suggest to open external links in a separate window which can be closed, or check page availabliity before click.

Tested on d-installer-live.x86_64-0.4.2-Build2.8.iso

![trap](https://user-images.githubusercontent.com/510119/198044847-b6767e0b-3da5-4601-aeeb-28e0ccb1b076.png)

**Comment by gautamkrishnar** [comment]
@imobachgs it is better to remove this link since there is no way for a user to navigate back. Can we remove it?

**Comment by imobachgs** [comment]
I consider that the links are useful, if you have an Internet connection. Actually, in the current version, you cannot install the system unless you have a working Internet connection.

What we can do is 1) open the link on a different tab or 2) disable the links if no connection is available. Does it make sense to you? Most probably, we will start implementing 1).

**Comment by imobachgs** [comment]
Finally, we have decided to just remove the link by now.

**Comment by 4sokol** [comment]
I've got the same issue: Browser window opens with the Internet connection error ("Browser window opens with the Internet connection error with no options to close the browser window or minimize it")with no options to close the browser window or minimize it
![repository_link](https://user-images.githubusercontent.com/72856789/200074769-bb0a7816-76fe-41dd-b675-54fb2cef18bf.png)
