### ISSUE TITLE
Find a better name for the project

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#275]
It is no secret that we are not happy with the current name (see the Q&A in the [initial announcement](https://yast.opensuse.org/blog/2022-01-18/announcing-the-d-installer-project). However, we have failed to find a good alternative.

There is an interesting [Twitter thread containing some suggestions](https://twitter.com/openSUSE/status/1584923604252299265). We would like to track this issue as it is becoming more relevant.

**Comment by lkocman** [comment]
Ideally the logo should be added also to https://github.com/openSUSE/artwork/tree/master/logos

**Comment by lkocman** [comment]
Here are suggestsions from the twitter https://etherpad.opensuse.org/p/names 
Now I leave the decision whether to pick one of the candiates to the YaST team.

**Comment by imobachgs** [comment]
Thanks a lot for all the suggestions. Unfortunately, we have not agreed on which should be the right name. By now, we are keeping "D-Installer", but we are open to receiving more proposals. What we did, was define a set of criteria that the new name should meet:

* obviously, it should be unique in our scope.
* easy to search for.
* avoid "competitive" names (like an Anaconda predator and so on).

**Comment by lkocman** [comment]
Suggesting to close the issue, you have all rights to keep the current name. I really hoped for "Current" being the choice :-)

**Comment by teohhanhui** [comment]
I don't know if you've received this feedback yet, but "agama" means religion in Indonesian and Malaysian at least. It'd be confusing for speakers of those languages (and potentially triggering).
