### ISSUE TITLE
No storage check

### ISSUE THREAD

**Issue by ggardet** [yast/d-installer#278]
I tested in qemu KVM, but I forgot to add an empty HDD image, so no storage have been found but the installer does not complain and if I click `Install`, it starts the process and finishes with `Congratulations! The installation on your machine is complete.` which is obviously wrong.

**Comment by imobachgs** [comment]
Thanks for your report!

You are right, D-Installer does check anything before starting, which is quite unfortunate. We expect to release some important changes to the partitioning area in the next month.
