### ISSUE TITLE
Installation of aarch64 Tumbleweed and Leap Micro 5.2 ends up on `grub>` prompt

### ISSUE THREAD

**Issue by ggardet** [yast/d-installer#279]
Installation of aarch64 Tumbleweed and Leap Micro 5.2 ends up on `grub>` prompt.
```
                             GNU GRUB  version 2.06

   Minimal BASH-like line editing is supported. For the first word, TAB   
   lists possible command completions. Anywhere else TAB lists possible   
   device or file completions.                                            


grub>
```

Note: aarch64 Leap 15.4 installation worked fine.

**Comment by imobachgs** [comment]
Hi @ggardet,

Would it be possible for you to gather YaST logs? After a failing installation, you might change to a console (ctrl+alt+f1), and log in with "root" (user) and "linux" (password). After that, typing `save_y2logs` should extract them for you.

Thank you!

**Comment by jreidinger** [comment]
I reproduce it and it failed with
```
2022-11-01 22:21:38 <1> localhost.localdomain(2427) [Ruby] lib/cheetah.rb(record_commands):163 Executing "/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg".
2022-11-01 22:21:52 <3> localhost.localdomain(2427) [Ruby] lib/cheetah.rb(log_stream_line):211 Error output: /usr/sbin/grub2-probe: error: failed to get canonical path of `LiveOS_rootfs'.
2022-11-01 22:21:52 <3> localhost.localdomain(2427) [Ruby] lib/cheetah.rb(record_status):183 Status: 1
2022-11-01 22:21:52 <3> localhost.localdomain(2427) [Ruby] yast2/execute.rb(rescue in popup_error):235 Execution of command "[["/usr/sbin/grub2-mkconfig", "-o", "/boot/grub2/grub.cfg"]]" failed.
Exit code: 1
Error output: /usr/sbin/grub2-probe: error: failed to get canonical path of `LiveOS_rootfs'.
```

**Comment by jreidinger** [comment]
the strange path comes from /proc/mounts
`LiveOS_rootfs / overlay rw,relatime,lowerdir=/run/overlay/rootfsbase,upperdir=/run/overlay/overlayfs/rw,workdir=/run/overlay/overlayfs/work 0 0`

So it is some overlayfs that confuse grub.

**Comment by jreidinger** [comment]
Another attempt to install failed with different issue that dracut is not available and looks like caused by mocked SpaceCalculation at https://github.com/yast/d-installer/blob/master/service/lib/dinstaller/dbus/y2dir/software/modules/SpaceCalculation.rb

For interested people I attach also y2logs from that attempt ( ignore initial dbus timeouts that is caused by systemd attempt to start service that timeout and then I start it manually )
[y2log-utSZfv.tar.gz](https://github.com/yast/d-installer/files/10094060/y2log-utSZfv.tar.gz)

**Comment by jreidinger** [comment]
And after another round of debugging it is now clear what cause this bug. It is repository definition. Only Leap 15.4 has aarch architecture as part of repositories in https://download.opensuse.org/distribution/leap/15.4/repo/oss/
On other hand MicroOS does not have aarch at all. And for TW it needs own repository in ports at https://download.opensuse.org/ports/aarch64/distribution/leap/15.4/

So for fix we will need to be able to define arch specific urls for repositories and also be able to specify products based on architecture as not all products are available on all architectures.

**Comment by jreidinger** [comment]
OK, just successfully verified that with modified d-installer.yml file that points to ports, TW can be installed and booted.

**Comment by jreidinger** [comment]
And one more good news. I found that we switch to Micro 5.3 and Micro5.3 has support for aarch64, so I will add it as part of fix for TW.
