### ISSUE TITLE
Qemu no d-bus enabled (cockpit)

### ISSUE THREAD

**Issue by bittin** [yast/d-installer#280]
Hello!

Tested in a QEMU VM via the Virtual machine thing in Cockpit and then it says D-bus is not enabled https://cdn.discordapp.com/attachments/545922654570414090/1035171151200133250/Skarmbild_fran_2022-10-27_14-40-21.png

**Comment by imobachgs** [comment]
The new ISO image should not have this problem. You can grab it here: https://build.opensuse.org/package/binaries/YaST:Head:D-Installer/d-installer-live/images

Thanks!
