### ISSUE TITLE
Disable firefox default password manager for the installer

### ISSUE THREAD

**Issue by gautamkrishnar** [yast/d-installer#283]
While installing, the installer asks the user to generate a secure password using firefox's default password manager. Showing it to the users is a bad UX since users don't have access to this generated password later. The only way to remember it is by writing it down.

![Screenshot 2022-10-29 at 6 36 33 PM](https://user-images.githubusercontent.com/8397274/198833385-b1f0f376-c5da-4d30-8cb2-fbc5ebec5fcb.png)

**Comment by imobachgs** [comment]
Thanks for give D-Installer a try and reporting issues. However, this issue is already reported (see #113). Unless you oppose, I am closing this one as a duplicate.
