### ISSUE TITLE
Currently the installer allows users to install OS without setting root and user accounts

### ISSUE THREAD

**Issue by gautamkrishnar** [yast/d-installer#285]
Currently, the installer allows users to install OS without setting root and user accounts

https://user-images.githubusercontent.com/8397274/198835505-2bf7c999-8e83-4df5-9b90-67adefb3e329.mov

The resulting tumbleweed installation is totally unusable as a result of this:
![Screenshot 2022-10-29 at 7 37 25 PM](https://user-images.githubusercontent.com/8397274/198835990-159e8900-a6b7-4a38-a576-2c287fe0273c.png)

### Expected behavior
- The installer should make it mandatory to set a root/user password before installing the OS
- The install button should be disabled otherwise

**Comment by imobachgs** [comment]
Thanks for the report. We have some related issues like #177 and #140. I will keep all of them open, but I expect they to be fixed altogether.
