### ISSUE TITLE
d-installer fails to start

### ISSUE THREAD

**Issue by drmpjz** [yast/d-installer#286]
Environment:
Virtualbox 6.1.22 on openSUSE 15.2 (yes I know, I need to update)
d-installer-live.x86_64-0.4.2-Build2.12.iso as Installmedium for new VM.
Boots up but Screen gets stuck with message:
Cannot connect to D-BUS

Pressing the reload button does not help.

On the same environment the "classic" installer for openSUSE 15.4 works without any problems

**Comment by drmpjz** [comment]
Looks similar to #280

**Comment by mmeiste** [comment]
I ran into same issue on sles12sp5, I switched to console ctrl+alt+f1 logged in as root (using easy password), then started:
systemctl start d-installer.service

used image d-installer-live.x86_64-0.4.2-Build2.10.iso

**Comment by jreidinger** [comment]
yeap, I think solving #287 can help as I also face it on slow arm emulation and basically issue is if probing takes longer then 1 second, then race condition with started services can happen.

**Comment by drmpjz** [comment]
@mmeiste : Do you have a hint where to find the easy password? I tried the (for me) obvious ones without success.

**Comment by imobachgs** [comment]
> @mmeiste : Do you have a hint where to find the easy password? I tried the (for me) obvious ones without success.

The "easy" password is "linux". :-)

**Comment by imobachgs** [comment]
The new ISO image should not have this problem. You can grab it here: https://build.opensuse.org/package/binaries/YaST:Head:D-Installer/d-installer-live/images

Thanks!

**Comment by drmpjz** [comment]
Tried the build of Dec 2nd 2022 16:51 - Installation could be started and finished. Issues with the installation will be reported in separate issue.
