### ISSUE TITLE
Language Picker dropdown is visibly stuck but seems to work behind the scene

### ISSUE THREAD

**Issue by signed-log** [yast/d-installer#288]
Host : Hyper-V generation 2 VM, 2vCores/4GB
Build : d-installer-live.x86_64-0.4.2-Build2.15.iso

When using the language picker, it appears that the drop-down is stuck :

- Scroll Wheel doesn't move anything
- The Scroll bar doesn't either

It seems to be registering the commands given but with strictly no visual feedback

If you select an entry (this will probably not be the wanted language) and reopen the dropdown, it moved to highlight the selected language but still be stuck

Using the keyboard to choose your language work (Typing `F` will land you to French)

**Comment by imobachgs** [comment]
Thanks for reporting. We will plan to fix this issue.

**Comment by signed-log** [comment]
Works for me (libvirt/qemu)
