### ISSUE TITLE
I like the old installer, here are multiple issues with the new

### ISSUE THREAD

**Issue by as-muncher** [yast/d-installer#297]
Hi, I actually like the old installer, I really do.  It's amazing what yast can do.  I've tried a number of installers for other distributions, including calamares, and find them rather mickey-mouse-like.  The old yast installer can actually figure out what to do for installing next to a Windows partition, and for writing the correct boot things, for choosing the filesystem, for choosing the software packages, to properly write the bootloader to the external hard drive when installing to an external hard drive and not write it to the internal hard drive, for choosing encryption, location,time zone, kernel paramters.  The old installer just does it right!!!  That's what I like about it, even though opensuse really is not my first choice of an every day linux distribution to use.  The one thing I'd want changed with the old installer, is that, when the user is at the last step, to commit to proceeding with the installation, that maybe there should be something there just verifying the write location again, like with name of the device, the size, USB or SCSI or what.

I would have written all this down maybe in the forum, but all I got was a link to a Google Drive document that wasn't in a useable form.

With the new installer:

1) After installing Tumbleweed, BIOS couldn't recognise the device, so I couldn't boot from it.  Mind you, I used d-installer in offline mode, so maybe it didn't even really install anything.

2) I couldn't figure out which was better for me - Tumbleweed or Leap.  They both mention stability, but who wouldn't want enterprise code that has been thoroughly tested, in Leap, and yet you all are thinking of discontinuing Leap, right?  One didn't really seem better than the other, but Leap seemed just a bit better because of well-tested enterprise code and stability.

3) Is it necessary to make an SSH root password?  I see it as an option, but there's no help or anything to tell the user why it's even important or not to have that password.

4) I like the installer now that shows you will be writing to _____, drive, drive size, connection type, which was a little better than the first installer.

5) I think you should give users the option of which installer to use, because I think many will prefer the old.

6) In the new one, there's no option to choose which filesystem to use, which is one of the most important things to do when installing because isn't it hard to change that after the system is installed?

7) With root password, ssh root password, user password, there's no second box to enter the password again to verify that you actually entered it the correct way the first time, and I think that's important.

8) What if you want the bootloader on the internal hard drive instead of the external hard drive (for some strange reason).  There's no option to do that with the new installer.

9) There's no option to encrypt the hard drive?  That's important too.

10) I like that a separate swap partition is not mentioned.  The thing with that is, if I install opensuse to an external hard drive, using a computer with only 4 GB of RAM and I choose to encrypt my hard drive, and thankfully the installer will also encrypt the swap partition, what if I then want to use that opensuse system on another computer, seeing that it is installed on an external hard drive?  Now I can't hibernate on the new system because my swap partition was only 4 GB and now I have 8 GB in the new system.  That's why I think it's better to have a hibernation file, a swap file, not a swap partition.

11) I think that the new installer uses up the screen better.  not so much white space.  The old installer had text that was way too small, and wasn't adjusting the size for the size of the screen.

**Comment by imobachgs** [comment]
Hi @as-muncher,

Thanks for your feedback. It is much appreciated. First of all, we do not have plans to phase out the old installer at this point. Time will tell if something changes in the future.

As @ancorgs commented, D-Installer is in an early stage of development so many features are still missing. Actually, we are working on a couple of things, including network configuration or storage management, for upcoming versions.

Anyway, take into account that D-Installer relies on YaST libraries, so it would be possible to leverage YaST capabilities where needed.

Now, about your specific points:

1. What do you mean by offline mode? No network connection? In that case, it won't work, but we should inform the user about that. We are working on a mechanism to inform the user about such situations.
2. We offer Leap because we want to try that we can install several distributions.
3. We definitely need to improve the UX of that section. The SSH password option is offered in the old installer too, but only if you decide not to create a first user. So I have created #298 to handle this issue.
4. More changes are expected in the storage area pretty soon.
5. No plans to phase out the current installer by now.
6. See point 4 :-)
7. We plan to go for #242 which, IMHO, is better than having two fields. What do you think?
8. That feature is missing (along with many bootloader features, like specifying a password).
9. See point 4 :-)
10. This point is not specific to D-Installer, isn't it? So you would like to have a hibernation file or a swap file instead of a swap partition, right?
11. I agree. Sure we can do it better, but in this stage of development, it looks good.

I hope I have clarified some of your questions.

**Comment by as-muncher** [comment]
@imobachgs Yes, I'd like to have a hibernation file or swap file instead of a swap partition for the reasons mentioned above.  With point 7, at this point, there's only one box for each password, so even if the last letter was shown on the screen at a time, I don't know.. maybe I guess that could work.  Just a thought, though, is that if someone is actually spying on a person's computer, say, through vnc or what not, that peeper could actually see the entire password as it is typed in.  With two fields, then at least the passwords are never shown and the person has to confirm the first password by entering it again.  

Truthfully, I'm not sure why you all are changing to a new installer.  I find yast amazing in what it can do.  I don't even know why you include Discover when that program is garbage in my opinion.  I mean, for Leap.  Yast has too much of a technical cost?  Honestly, I've tried a number of installers for other linux distributions with so much hassle.  I've tried oracle's and they use anaconda, I think, and you do this or that and the installer can't even proceed.  Fedora I think uses it too and it's hard to use, doesn't figure things out the way yast does.  I use calamares and sometimes it's good, like with Manjaro when you can choose a hibernation/swap file instead of a partition, but then on other distros, it doesn't give enough options, like installing to an external hard drive, or have an option to create a root password, to not always be administrator, and so forth.  My gripe right now with opensuse is with the media and network not working on an older computer and no automatic bug reporting tool working, unless it's done in the background.  If you can tell me whom to send a file to, I will send you a file which opens in firefox and will hang your system, so maybe you all can figure that out.

Anyways, sorry to have to put that all here, as I haven't yet checked out the forums or signed up for opensuse's bugzilla.  I guess I just like that yast works right away with no hassle.  Many thanks.

**Comment by imobachgs** [comment]
@as-muncher I understand your concerns. We wrote some notes about [why we are building](https://github.com/yast/d-installer#why-a-new-installer) a new installer, but we will try to communicate our reasons better.

About using a file as swap, I do not know if we have concrete plans. @ancorgs might know better than me ;-)

I would say that the best way to report a bug for openSUSE is through our [Bugzilla instance](https://bugzilla.opensuse.org/). It would be great if you give it a try :-)

Thanks!

PS: I have added your observation about introducing password as [a comment](https://github.com/yast/d-installer/issues/242#issuecomment-1311063384) on #242.

**Comment by as-muncher** [comment]
@imobachgs  Ok, thanks!!  :)  
The only reason I'd be looking for a hibernation file is just because when you move your system to one that has more RAM, then you can't hibernate anymore because your swap partition isn't big enough.  Thanks for reposting the link for why you're creating a new installer.

**Comment by kobliha** [comment]
Just a few notes...

- The usage of swap files is nothing new and proven to be generally working, even zram should work there
- As the file is of a fixed length at a defined place on the disk, it's (considering the speed) probably very similar to using a separate partition
- There might be a problem with resuming from that swap if it's on an encrypted partition, but should be working, according to e.g., https://forum.manjaro.org/t/hibernate-with-swapfile-on-encrypted-partition/70507
- Something that would need to be taken into account is the size of the real partition/LVM volume/... where it's placed as that might involve the weight put on it when proposing the partitioning layout
- Plus there might be issues when incorrectly reporting enough space for packages requested by the Packages Proposal
