### ISSUE TITLE
QEMU test

### ISSUE THREAD

**Issue by RafaelLinux** [yast/d-installer#303]
I was just trying new installer thru QEMU. It loads, but stays forever in this page:

![imagen](https://user-images.githubusercontent.com/13048959/201670818-4f30cb0a-25d2-4c94-b6f2-732807757ab5.png)

showing grey bars animation forever. It shows no errors or "not detected" storage devices, simply, show nothing about disks, but it let user click on "Install".

;)

**Comment by imobachgs** [comment]
Hi @RafaelLinux,

Thanks for your report. Most probably, there might be some problem probing for disks to perform the installation. We plan to release a new version this week that implements #299 and we might get some additional information then. If you do not mind, I will keep this bug report open until you can give it a try to the new version.

**Comment by imobachgs** [comment]
Yes, it is kind of "expected". The UI is not translated yet. Selecting a language just changes the software selection to install the packages of that language by now.

**Comment by imobachgs** [comment]
Hi,

We have released a new version of the ISO. It would be nice if you could give it a try. If it still gets blocked, it would be helpful if you extract the logs so we can inspect them. To do that, you need to change to a text console, log in as root (root/linux) and run the `save_y2logs` command.

You can grab the new version from https://build.opensuse.org/package/binaries/YaST:Head:D-Installer/d-installer-live/images

Thanks in advance!

**Comment by RafaelLinux** [comment]
Much better. It detects there is no storage. However, "Install" button is clickable (I think it should not be) so an error is showed.
![imagen](https://user-images.githubusercontent.com/13048959/203151181-aedf96a8-efa2-4fdf-9948-23a8fe5e01bd.png)

**Comment by imobachgs** [comment]
Hi @RafaelLinux,

Actually, it works as expected. We decided not to disable the button. Otherwise, we should display the "errors" as soon as the page is loaded before the user does anything, and it did not look nice. Of course, we are open to change the behavior (actually 

Anyway, I am curious about why D-Installer does not find a suitable device.

**Comment by RafaelLinux** [comment]
About "suitable device", I can tell you that even "openSUSE-Tumbleweed-KDE-Live-x86_64-Snapshot20221014-Media.iso" doesn't show any device at all. It seems QEMU launch it without any device emulation  ;)
