### ISSUE TITLE
Missing firmware after installation

### ISSUE THREAD

**Issue by joseivanlopez** [yast/d-installer#356]
[Firmware packages](https://build.opensuse.org/request/show/1039959) were added to the live ISO image in order to make possible to configure network connections during the installation. But firmware packages are still missing in the installed system. As result, the network config is correctly copied to the target system but there is no active connection there.

**Comment by lslezak** [comment]
The firmware packages were not installed because the ALP repository (the one intended for the end users) was missing all firmware packages. Frederic fixed that issue.
