### ISSUE TITLE
Remote Installation: $Server:9090 gets you into Cockpit instead of D-Installer

### ISSUE THREAD

**Issue by kobliha** [yast/d-installer#365]
Obviously, as D-Installer uses Cockpit, you logically get into Cockpit instead of D-Installer. When logged in, you can select D-Installer in the menu, but it does not open full-screen anyway.

IMO, it should be the other way round. D-Installer should be the default app being open fullscreen and Cockpit (if at all) should be possible to access on request only.

In other words, https://$IP:9090/ should point to D-Installer

See also https://github.com/yast/d-installer/issues/377

**Comment by imobachgs** [comment]
It is doable by using the `Shell` option. The following `cockpit.conf` would force you to go through the `D-Installer` module:

```
[WebService]
Shell = /d-installer/index.html
```

And you can still access Cockpit through `https://localhost:9090/cockpit/@localhost/shell/index.html`.

These days, D-Installer already adapts Cockpit configuration while booting (if needed), so it is just a matter of adjusting this value too (according to a configuration value).

**Comment by imobachgs** [comment]
Actually, as suggested by @joseivanlopez, just dropping the correct `cockpit.conf` file in the Live media is enough. D-Installer should respect those values and change the SSL ones if needed.

**Comment by imobachgs** [comment]
Implemented in #380. Thanks!
