### ISSUE TITLE
Add a "hamburguer" menu

### ISSUE THREAD

**Issue by imobachgs** [yast/d-installer#395]
There are some actions like downloading the logs or changing the product that do not fit into any of the sections. And we expect to have more in the future (e.g., documentation links). In order to accommodate them, we have decided to add a hamburger menu.

**Comment by dgdavid** [comment]
I've added the basic infrastructure for this in #379 in order to avoid extra work relocating the _Download logs_ button/action twice.

In that first step, I moved the _Change selected product_ action and the footer links to the sidebar too. Now, we have an entry point to discuss/evaluate the approach and where each action should really be placed.

**Comment by dgdavid** [comment]
From the top of my head, here are a few things to be addressed when working on this:

* Use the proper element for the action to open/close the menu. It is a link now, but it should probably be a button.

  This has a relation with the mentioned "To fix the misuse of buttons/links" mentioned at https://github.com/yast/d-installer/pull/391 and also with https://github.com/yast/d-installer/pull/379#discussion_r1073356553

* Give some love to the usability

  - Put those links/actions into a list

  - Add needed aria attributes to avoid the screen reader reading its content when the menu is in the collapse state. https://www.boia.org/blog/are-hamburger-menus-bad-for-accessibility could be worthwhile reading.

* Decide on links/informationon to hold there. 

   Do we want to keep the IP information there? If so, should we use a skeleton placeholder for that entry while the information is being read? Etc.

* Decide if we're going to create a layout slot to allow pages add contextual content/actions to the sidebar

---


There are probably a few more things that will arise as soon as we resume the work in that area.

**Comment by imobachgs** [comment]
The hamburguer is already there. If there are pending issues, we should add a to-do list to this issue or open independent ones.

**Comment by dgdavid** [comment]
> Use the proper element for the action to open/close the menu. It is a link now, but it should probably be a button.

Done at https://github.com/yast/d-installer/pull/436

**Comment by imobachgs** [comment]
Done, so let's close it.
