### ISSUE TITLE
Login to development UI

### ISSUE THREAD

**Issue by tacerus** [yast/d-installer#41]
Hi,

thank you for the cool project!

building using `npm run build` and serving the full program using Cockpit works as expected - login is possible using a regular system user.
However attempting to log in with the same credentials to a development instance (`npm run dev`) will present a "401: Authentication failed" in the browser console, with the following being printed to the system journal:

```
Feb 24 20:57:41 localhost cockpit-ws[13471]: json_object_get_string_member: assertion 'node != NULL' failed                                       
Feb 24 20:57:41 localhost systemd-logind[705]: New session 13 of user georg.                                                                      
Feb 24 20:57:41 localhost systemd[1]: Started Session 13 of User georg.                                                                           
Feb 24 20:57:41 localhost cockpit-session[13474]: pam_unix(cockpit:session): session opened for user georg(uid=1000) by (uid=0)                   
Feb 24 20:57:41 localhost polkitd[733]: Registered Authentication Agent for unix-session:13 (system bus name :1.143 [cockpit-bridge], object path 
/org/freedesktop/PolicyKit1/AuthenticationAgent, locale C.UTF-8)                                                                                  
Feb 24 20:57:41 localhost sudo[13487]:    georg : PWD=/run/user/1000 ; USER=root ; COMMAND=/usr/bin/cockpit-bridge --privileged                   
Feb 24 20:57:41 localhost sudo[13487]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)                                                                
Feb 24 20:57:55 localhost polkitd[733]: Unregistered Authentication Agent for unix-session:13 (system bus name :1.143, object path /org/freedeskto
p/PolicyKit1/AuthenticationAgent, locale C.UTF-8)                                                                                                 
Feb 24 20:57:55 localhost sudo[13487]: pam_unix(sudo:session): session closed for user root                                                       
Feb 24 20:57:55 localhost cockpit-session[13474]: pam_unix(cockpit:session): session closed for user georg                                        
Feb 24 20:57:56 localhost systemd[1]: session-13.scope: Deactivated successfully.                                                                 
Feb 24 20:57:56 localhost systemd-logind[705]: Session 13 logged out. Waiting for processes to exit.                                              
Feb 24 20:57:56 localhost systemd-logind[705]: Removed session 13.                                                                                
Feb 24 20:58:00 localhost cockpit-ws[13471]: json_object_get_string_member: assertion 'node != NULL' failed
```

Looks like cockpit is authenticating me, but somehow it's not interpreted as a "success"?
Or are there some predefined credentials for the development instance? I noticed in the script for usage on the live .iso just a regular user named `linux` is created, hence I assumed a regular Unix user should be usable on a full system as well - but maybe I missed something.

The `json_object_get_string_member: assertion 'node != NULL' failed` errors from `cockpit-ws` appear in the production build as well, hence I think they are not relevant.

This was attempted on a fresh install of Tumbleweed after using `setup.sh`.
```
$ cockpit-bridge --version
Version: 251.3
$ more /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20220223"
```

Thanks for any ideas on this!

Georg
(acidsys in IRC)

**Comment by tacerus** [comment]
Hi Imo,

thanks for elaborating! I think I got that, however based on

> Actually, if you reload the installer after being authenticated, you should not see that error anymore (until you log out).

 I am not sure if I explained correctly - in the production instance login and authentication using Cockpit works perfectly. However in the development run the page will just reload upon clicking "Login", putting me back to the login prompt. I never reach anything more than the logon page in the dev run:

![image](https://user-images.githubusercontent.com/5121046/155747039-c503e085-e213-4b8b-8581-173965e58e76.png)


I thought maybe there was a way to log in to a dev instance the same way as to a production instance, so the UI which shows "after" the logon page can be worked on without having to rebuild it after every change.

**Comment by imobachgs** [comment]
Oh, you are using the `new-dbus-api` branch, right? Bear in mind that the branch is broken currently as we implement and migrate to the new D-Bus interface 😅 

I have been working on adapting the language selection (I will open a PR later) and I was able to log into my development system (although I get the 401 initially). Let's keep the issue open for further investigation, I will try to reproduce the issue in a VM.

BTW, nice screenshot 😄 

PS: credentials in the setup.sh are `linux` / `linux`.

**Comment by tacerus** [comment]
I'm on the master branch, yes.
I'll try it again on a live system, with the script-created `linux` user - however I did not find anything that would be different on my full/disk-installed Tumbleweed system and the regular Unix users on it.

> BTW, nice screenshot smile

Thanks ;-)

**Comment by tacerus** [comment]
I now tried it in a Tumbleweed live environment using the `deploy.sh` variant. With it the authentication works as expected on the first try - both with the scripted `linux` user, as well as with additional users.

It is not quite clear to me what the live environment does differently - the only thing that is apparently different is the use of the D-Installer RPM package from the repository versus the development run with `bundle` and `npm` - however the authentication should be taken care of by Cockpit, which is installed from the repositories in both variants and should be the same and behave the same in both constellations.

**Comment by imobachgs** [comment]
Hi @tacerus,

Sorry for taking too much time to answer, somehow I overlooked your response.

About the differences, you are right: in both cases, Cockpit takes care of the authentication (through PAM). But there is a difference between `setup.sh` and `deploy.sh`.

* `setup.sh` script does not set any password. The idea is that you can use such a script to set up the development environment in your machine. If you use it in the live image, you can log in without any password (just the "linux" or the "root" user).
* The `deploy.sh` is used to set up D-Installer in a live image, using packages instead of the contents of the repository. In this case, we decided to set the password "linux" for the "linux" user (for testing purposes).

Please, let me now if it still does not work for you.

**Comment by tacerus** [comment]
Hi,

no problem, and thanks for elaborating!
I was aware of the differences, however could not get a user in a non-live system to authenticate to an instance installed using `setup.sh`.
I noticed there have been quite a few commits lately though, so I guess I should just try again - maybe something relevant changed! I'll report back if it still does not work.
