### ISSUE TITLE
Cannot boot after installing onto secondary disk

### ISSUE THREAD

**Issue by mchf** [yast/d-installer#416]
## Scenario

1) Running d-installer in a TW virtual machine. Available disks sda, sdb. System running from sda, sdb empty (even non-partitioned)
2) d-installer used to install TW product onto /dev/sdb
3) installation came to the end with no problem, asking for reboot
4) Turned VM with d-installer off, attached disk image of sdb to another machine to boot installed system
5) installed system didn't boot, crashed into grub rescue
![d-installer-cannot_boot_installed_target](https://user-images.githubusercontent.com/1579239/216023582-d859da7c-7620-4e40-a8bd-0d478bc97bac.png)

## Details from debugging

- I was able to start normal mode manually from grub rescue using
```
grub rescue> set prefix=(hd0,gpt2)/@/boot/grub2
grub rescue> set root=(hd0,gpt2)
grub rescue> insmod normal
grub rescue> normal
```
- however (hd0,gpt2)/@/boot contains only grub2 folder but no kernel and so on. See
![d-installer-grub_rescue](https://user-images.githubusercontent.com/1579239/216027120-57e08259-70eb-46b6-972e-ee1384e12b20.png)

**Comment by mchf** [comment]
The issue is caused by using the d-installer for unsupported use case.

Core of the issue is caused by the fact that installation is targeted against second disk /dev/sdb in grub's word (hd1). So, when the sdb disk image is later detached and inserted into another machine it changes its relative name to /dev/sda resp (hd0) and grub gets confused.

Here is how you can boot the target from grub rescue:
```
grub2 rescue> set root=(hd0,gpt2)
grub2 rescue> set prefix=(hd0,gpt2)/@/boot/grub2
grub2 rescue> insmod normal
grub2 rescue> normal
grub2> insmod btrfs
grub2> linux /@/.snapshots/1/snapshot/boot/vmlinuz root=/dev/sda2
grub2> initrd /@/.snapshots/1/snapshot/boot/initrd
grub2> boot
```
to make it permanent run as root:
```
# grub2-install /dev/sda
# grub2-mkconfig -o /boot/grub2/grub.cfg
````

**Comment by mchf** [comment]
As I tried to explain, d-installer "works as expected" here. For those who really wants / needs to use the d-installer in a way as described in the description there is a workaround mentioned above.

I've nothing more to add, so closing.

**Comment by imobachgs** [comment]
Very useful information. Thanks a lot, @mchf. I will move this tip to the project's wiki.

**Comment by imobachgs** [comment]
Summarized [here](https://github.com/yast/d-installer/wiki/Tips-and-tricks#installing-onto-a-secondary-disk). Thanks!
