### ISSUE TITLE
Remove "{S|s}ettings from the Page titles accessed through the home page

### ISSUE THREAD

**Issue by jknphy** [yast/d-installer#481]
There is no need to call the new pages es "* Settings" from the user perspective it looks like you go to some places, got the same icon same text but some other postfix which might not be the place you requested initially, they are all Settings, so there is not need to include the word 'setting' in each title. Besides than in Localizaton is in lower letter 'settings' and in other is in capital letter "Settings" being the later the correct one, but anyway superfluous. Also when going to Storage Settings there is a section for Settings, but there is also Device, so making it general should be more clear to cover all.wdyt?

**Comment by imobachgs** [comment]
Thanks for the report! Fixed in #482.
